# First install module community.docker
# ansible-galaxy collection install community.docker

---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_database: "problemsetters"
    mysql_user: "problemsetter"
    mysql_password: "11111"

  tasks:
    - name: Create container db
      community.docker.docker_container:
        name: db
        state: started
        image: mysql:latest
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"

    - name: Create container web
      community.docker.docker_container:
        name: web
        state: started
        image: problemsetters/801133-ansible
        pull: true
        links:
          - "db:db"
        ports:
          - "8000:80"
        env:
          MYSQL_HOSTNAME: "db"
          MYSQL_ROOT_USER: "{{ mysql_user }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
