apiVersion: v1
kind: Namespace
metadata:
  name: hacker-company
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hacker-company
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hacker-company
spec:
  selector:
    role: frontend
